parameters:
  - name: "projectName"
    type: string
  - name: "framework"
    type: string
    values:
      - net8.0
      - net8.0-windows
      - net9.0
      - net9.0-windows
      - net10.0
      - net10.0-windows
  - name: "projectParentDirectory"
    type: string

stages:
  - stage: Build
    displayName: "Build n Pack"
    jobs:
      - template: buildNPack.yml
        parameters:
          projectName: ${{ parameters.projectName }}
          framework: ${{ parameters.framework }}
          projectParentDirectory: ${{ parameters.projectParentDirectory }}

  - stage: DeployPrerelease
    displayName: "Deploy Prerelease"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
    environment: develop
    dependsOn: Build
    jobs:
      - template: pushNuget.yml
        environment: develop

  - stage: DeployRelease
    displayName: "Deploy Release"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    environment: main
    dependsOn: Build
    jobs:
      - template: pushNuget.yml
        environment: main
