parameters:
  - name: "projects"
    type: object
    default: []
  - name: "framework"
    type: string
    values:
      - net8.0
      - net8.0-windows
      - net9.0
      - net9.0-windows
      - net10.0
      - net10.0-windows
  - name: "projectParentDirectory"
    type: string

jobs:
  - job: BuildNPack
    pool:
      name: x-agentpool
    workspace:
      clean: all
    variables:
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: UseDotNet@2
        displayName: "Use .Net Core sdk from global.json"
        inputs:
          packageType: "sdk"
          useGlobalJson: true
          includePreviewVersions: true

      - ${{ each project in parameters.projects }}:
          - task: DotNetCoreCLI@2
            displayName: "dotnet restore ${{ project }}"
            inputs:
              command: restore
              projects: ${{ parameters.projectParentDirectory }}${{ project }}/${{ project }}.csproj
              feedsToUse: config
              nugetConfigPath: ${{ parameters.projectParentDirectory }}NuGet.config

          - task: DotNetCoreCLI@2
            displayName: "dotnet build ${{ project }}"
            inputs:
              projects: ${{ parameters.projectParentDirectory }}${{ project }}/${{ project }}.csproj
              arguments: "--configuration $(BuildConfiguration)"

          - task: DotNetCoreCLI@2
            displayName: "dotnet test ${{ project }}"
            inputs:
              command: test
              projects: ${{ parameters.projectParentDirectory }}${{ project }}.Tests/${{ project }}.Tests.csproj
              arguments: '--configuration $(BuildConfiguration) -s $(System.DefaultWorkingDirectory)/${{ parameters.projectParentDirectory }}.runsettings --framework ${{ parameters.framework }} --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
              publishTestResults: true
            continueOnError: true

          - task: DotNetCoreCLI@2
            displayName: "dotnet custom pack release"
            inputs:
              command: custom
              projects: ${{ parameters.projectParentDirectory }}${{ project }}/${{ project }}.csproj
              custom: pack
              arguments: "-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory) --no-build"
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

          - task: DotNetCoreCLI@2
            displayName: "dotnet custom pack preview"
            inputs:
              command: custom
              projects: ${{ parameters.projectParentDirectory }}${{ project }}/${{ project }}.csproj
              custom: pack
              arguments: "-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory) --no-build --version-suffix $(Build.SourceBranchName)"
            condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))

      #- task: PublishCodeCoverageResults@2
      # displayName: "Publish code coverage report"
      #inputs:
      # summaryFileLocation: "$(Agent.TempDirectory)/**/coverage.cobertura.xml"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: $(Build.SourceBranchName)"
        inputs:
          ArtifactName: "$(Build.SourceBranchName)"
        condition: succeededOrFailed()
