parameters:
  - name: "projects"
    type: object
    default: []
  - name: "framework"
    type: string
    values:
      - net8.0
      - net8.0-windows
      - net9.0
      - net9.0-windows
      - net10.0
      - net10.0-windows
  - name: "projectParentDirectory"
    type: string

stages:
  - stage: Build
    displayName: "Build n Pack ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}"
    jobs:
      - template: buildNPack.yml
        parameters:
          projects: ${{ parameters.projects }}
          framework: ${{ parameters.framework }}
          projectParentDirectory: ${{ parameters.projectParentDirectory }}

  - stage: Deploy
    displayName: "Deploy ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}"
    dependsOn: Build
    jobs:
      - template: pushNuget.yml
