parameters:
  - name: projectName
    type: string
  - name: framework
    type: string
    values:
      - net8.0
      - net8.0-windows
      - net9.0
      - net9.0-windows
      - net10.0
      - net10.0-windows
  - name: projectParentDirectory
    type: string

jobs:
  - job: Build
    displayName: "Build n Pack"
    steps:
      - template: buildNPack.yml
        parameters:
          projectName: ${{ parameters.projectName }}
          framework: ${{ parameters.framework }}
          projectParentDirectory: ${{ parameters.projectParentDirectory }}

  - job: DeployPrerelease
    displayName: "Deploy Prerelease"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
    steps:
      - download: current
        artifact: Nuget-Package
      - template: pushNuget.yml

  - job: DeployRelease
    displayName: "Deploy Release"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    steps:
      - download: current
        artifact: Nuget-Package
      - template: pushNuget.yml
