jobs:
  - job: PushNuget
    pool:
      name: x-agentpool
    variables:
      - group: ApiKeys

    steps:
      - task: DownloadPipelineArtifact@2
        displayName: "Download $(Build.SourceBranchName) Artifact"
        inputs:
          artifact: "$(Build.SourceBranchName)"
          path: "$(Pipeline.Workspace)/$(Build.SourceBranchName)"

      - task: UseDotNet@2
        displayName: "Use .Net Core sdk from global.json"
        inputs:
          useGlobalJson: true
          includePreviewVersions: true

      - task: DotNetCoreCLI@2
        displayName: "dotnet push evilfeed"
        inputs:
          command: push
          packagesToPush: "$(Pipeline.Workspace)/$(Build.SourceBranchName)/*.nupkg"
          publishVstsFeed: "652346b9-9a10-49f8-a49a-f79b3ec66045"
        continueOnError: true

      - task: DotNetCoreCLI@2
        displayName: "dotnet push MyGet"
        inputs:
          command: custom
          custom: nuget
          arguments: "push $(Pipeline.Workspace)/$(Build.SourceBranchName)/*.nupkg --api-key $(MyGet) --source https://www.myget.org/F/evilbaschdi/api/v3/index.json"
        continueOnError: true
