jobs:
  - job: PushNuget
    pool:
      name: x-agentpool
    variables:
      - group: ApiKeys

    steps:
      - task: DownloadPipelineArtifact@2
        displayName: "Download $(Build.SourceBranchName) Artifact"
        inputs:
          artifact: "$(Build.SourceBranchName)"
          path: "$(Pipeline.Workspace)/$(Build.SourceBranchName)"

      - task: UseDotNet@2
        displayName: "Use .Net Core sdk from global.json"
        inputs:
          useGlobalJson: true
          includePreviewVersions: true

      - task: DotNetCoreCLI@2
        displayName: "dotnet push evilfeed"
        inputs:
          command: push
          packagesToPush: "$(Pipeline.Workspace)/$(Build.SourceBranchName)/*.nupkg"
          publishVstsFeed: "652346b9-9a10-49f8-a49a-f79b3ec66045"
        continueOnError: true

      - task: Bash@3
        displayName: "dotnet push MyGet"
        inputs:
          targetType: "inline"
          script: |
            packagePath="$(Pipeline.Workspace)/$(Build.SourceBranchName)"
            echo "Looking for packages in: $packagePath"

            # Find all .nupkg files
            packages=$(find "$packagePath" -name "*.nupkg" -type f)

            if [ -z "$packages" ]; then
              echo "No .nupkg files found in $packagePath"
              exit 0
            fi

            echo "Found packages to push:"
            echo "$packages"

            # Push each package individually
            for package in $packages; do
              echo "Pushing package: $(basename "$package")"
              dotnet nuget push "$package" --api-key "$(MyGet)" --source "https://www.myget.org/F/evilbaschdi/api/v3/index.json" --skip-duplicate

              if [ $? -ne 0 ]; then
                echo "Warning: Failed to push $(basename "$package"), but continuing with other packages..."
              else
                echo "Successfully pushed $(basename "$package")"
              fi
            done
        continueOnError: true
